
CXXFLAGS = -I/home/hum/Projects/boost/libs/iostreams/example \
	   -I/home/hum/local/include

all:
	g++ -o shell_comments_filter $(CXXFLAGS) shell_comments_filter.cpp

clean:
	rm -rf shell_comments_filter shell_comments_output_filter.txt

